python3 run.py
python3 animation.py -r ./File_gif/CEM_Ackley_2.json -s ./File_save -start 1 -end 4
python3 animation.py -r ./File_gif/CEM_Ackley_2.json -s ./File_save -start 4 -end 8
python3 animation.py -r ./File_gif/CEM_Michalewicz_2.json -s ./File_save -start 1 -end 4
python3 animation.py -r ./File_gif/CEM_Michalewicz_2.json -s ./File_save -start 4 -end 8
python3 animation.py -r ./File_gif/CEM_Rosenbrock_2.json -s ./File_save -start 1 -end 4
python3 animation.py -r ./File_gif/CEM_Rosenbrock_2.json -s ./File_save -start 4 -end 8
python3 animation.py -r ./File_gif/CEM_Sphere_2.json -s ./File_save -start 1 -end 4
python3 animation.py -r ./File_gif/CEM_Sphere_2.json -s ./File_save -start 4 -end 8
python3 animation.py -r ./File_gif/CEM_Zakharov_2.json -s ./File_save -start 1 -end 4
python3 animation.py -r ./File_gif/CEM_Zakharov_2.json -s ./File_save -start 4 -end 8
python3 animation.py -r ./File_gif/DE_Ackley_2.json -s ./File_save -start 1 -end 4
python3 animation.py -r ./File_gif/DE_Ackley_2.json -s ./File_save -start 4 -end 8
python3 animation.py -r ./File_gif/DE_Michalewicz_2.json -s ./File_save -start 1 -end 4
python3 animation.py -r ./File_gif/DE_Michalewicz_2.json -s ./File_save -start 4 -end 8
python3 animation.py -r ./File_gif/DE_Rosenbrock_2.json -s ./File_save -start 1 -end 4
python3 animation.py -r ./File_gif/DE_Rosenbrock_2.json -s ./File_save -start 4 -end 8
python3 animation.py -r ./File_gif/DE_Sphere_2.json -s ./File_save -start 1 -end 4
python3 animation.py -r ./File_gif/DE_Sphere_2.json -s ./File_save -start 4 -end 8
python3 animation.py -r ./File_gif/DE_Zakharov_2.json -s ./File_save -start 1 -end 4
python3 animation.py -r ./File_gif/DE_Zakharov_2.json -s ./File_save -start 4 -end 8